spring.application.name=Multivender-e-commerce-marketplace
spring.datasource.url=jdbc:mysql://localhost:3306/Shubham
spring.datasource.username=root
spring.datasource.password=Rishu@194

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true